# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86e575dbc6c35f7e7695181a92c70c8a91014734808d003f707329d2a083ac5ef6094b72f04ad9f413e25a282ca4b04363fb98b978f53c3d61469459872ca869

test:
  secret_key_base: 3626e5d9c35b010394eddd475a9eaa0eedd20cbdb40500fb91726bc1f96f9cf5ea2334b14e96d5fa08480eecb9ae0cef2acc7d4246219954b0adcc1323871561

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
